/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tours: Tour;
    destinations: Destination;
    'promo-banners': PromoBanner;
    testimonials: Testimonial;
    'gallery-items': GalleryItem;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    'promo-banners': PromoBannersSelect<false> | PromoBannersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'touriza-settings': TourizaSetting;
  };
  globalsSelect: {
    'touriza-settings': TourizaSettingsSelect<false> | TourizaSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super_admin' | 'admin' | 'editor' | 'viewer';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  title: string;
  slug: string;
  category: 'europe' | 'asia' | 'middle-east' | 'africa' | 'americas' | 'oceania' | 'domestic';
  region: string;
  destination?: string | null;
  /**
   * VD: 12N/11Đ
   */
  duration?: string | null;
  departureDate?: string | null;
  /**
   * VND — để trống nếu "Liên hệ"
   */
  price?: number | null;
  /**
   * VD: Liên hệ
   */
  priceLabel?: string | null;
  badge?: ('hot' | 'new' | 'spring-2026' | 'none') | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  fallbackEmoji?: string | null;
  externalUrl?: string | null;
  featured?: boolean | null;
  order?: number | null;
  /**
   * VD: Copenhagen → Oslo → Stockholm
   */
  route?: string | null;
  overview?: string | null;
  highlights?:
    | {
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  itinerary?:
    | {
        day: string;
        title: string;
        description?: string | null;
        chip?: string | null;
        tags?:
          | {
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  tourCode?: string | null;
  airline?: string | null;
  departureFrom?: string | null;
  hotelInfo?: string | null;
  visaInfo?: string | null;
  insuranceInfo?: string | null;
  tourType?: string | null;
  depositNote?: string | null;
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  excludes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  terms?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  slug: string;
  country?: string | null;
  tourCount?: number | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  fallbackEmoji?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-banners".
 */
export interface PromoBanner {
  id: number;
  title: string;
  tag?: string | null;
  overlayStyle?: ('dark' | 'green' | 'blue') | null;
  subtitle?: string | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  gradientFrom?: string | null;
  gradientTo?: string | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  authorLocation?: string | null;
  tourName?: string | null;
  authorCompany?: string | null;
  avatarVariant?: ('av1' | 'av2' | 'av3' | 'av4' | 'av5' | 'av6') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  location: string;
  guestName?: string | null;
  caption?: string | null;
  likeCount?: number | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  size?: ('normal' | 'wide' | 'tall') | null;
  hasInstagram?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  content: string;
  metaDescription?: string | null;
  about?: {
    heroBadge?: string | null;
    heroImageUrl?: string | null;
    imageBadgeTitle?: string | null;
    imageBadgeText?: string | null;
    stats?:
      | {
          icon?: string | null;
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    introTitle?: string | null;
    introParagraphs?:
      | {
          html: string;
          id?: string | null;
        }[]
      | null;
    coverageIntro?: string | null;
    coverage?:
      | {
          icon?: string | null;
          iconColor?: ('green' | 'blue' | 'orange' | 'purple' | 'teal' | 'yellow') | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    mottoLabel?: string | null;
    mottoParts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    commitmentsIntro?: string | null;
    commitments?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    closingTitle?: string | null;
    closingParagraphs?:
      | {
          html: string;
          id?: string | null;
        }[]
      | null;
    closingSign?: string | null;
  };
  contact?: {
    heroBadge?: string | null;
    heroDescription?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    mapEmbedUrl?: string | null;
    workingHours?:
      | {
          day: string;
          time: string;
          isOpen?: boolean | null;
          id?: string | null;
        }[]
      | null;
    afterHoursNote?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'promo-banners';
        value: number | PromoBanner;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  region?: T;
  destination?: T;
  duration?: T;
  departureDate?: T;
  price?: T;
  priceLabel?: T;
  badge?: T;
  image?: T;
  imageUrl?: T;
  fallbackEmoji?: T;
  externalUrl?: T;
  featured?: T;
  order?: T;
  route?: T;
  overview?: T;
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  itinerary?:
    | T
    | {
        day?: T;
        title?: T;
        description?: T;
        chip?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        featured?: T;
        id?: T;
      };
  tourCode?: T;
  airline?: T;
  departureFrom?: T;
  hotelInfo?: T;
  visaInfo?: T;
  insuranceInfo?: T;
  tourType?: T;
  depositNote?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excludes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  terms?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  tourCount?: T;
  image?: T;
  imageUrl?: T;
  fallbackEmoji?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-banners_select".
 */
export interface PromoBannersSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  overlayStyle?: T;
  subtitle?: T;
  ctaLabel?: T;
  ctaLink?: T;
  gradientFrom?: T;
  gradientTo?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorLocation?: T;
  tourName?: T;
  authorCompany?: T;
  avatarVariant?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  location?: T;
  guestName?: T;
  caption?: T;
  likeCount?: T;
  image?: T;
  imageUrl?: T;
  size?: T;
  hasInstagram?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  content?: T;
  metaDescription?: T;
  about?:
    | T
    | {
        heroBadge?: T;
        heroImageUrl?: T;
        imageBadgeTitle?: T;
        imageBadgeText?: T;
        stats?:
          | T
          | {
              icon?: T;
              value?: T;
              label?: T;
              id?: T;
            };
        introTitle?: T;
        introParagraphs?:
          | T
          | {
              html?: T;
              id?: T;
            };
        coverageIntro?: T;
        coverage?:
          | T
          | {
              icon?: T;
              iconColor?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        mottoLabel?: T;
        mottoParts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        commitmentsIntro?: T;
        commitments?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        closingTitle?: T;
        closingParagraphs?:
          | T
          | {
              html?: T;
              id?: T;
            };
        closingSign?: T;
      };
  contact?:
    | T
    | {
        heroBadge?: T;
        heroDescription?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        addressLine1?: T;
        addressLine2?: T;
        mapEmbedUrl?: T;
        workingHours?:
          | T
          | {
              day?: T;
              time?: T;
              isOpen?: T;
              id?: T;
            };
        afterHoursNote?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "touriza-settings".
 */
export interface TourizaSetting {
  id: number;
  siteName?: string | null;
  logoUrl?: string | null;
  logo?: (number | null) | Media;
  topbar?: {
    hotline?: string | null;
    email?: string | null;
    address?: string | null;
  };
  hero?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    primaryCta?: string | null;
    secondaryCta?: string | null;
    imageUrl?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  social?: {
    facebook?: string | null;
    zalo?: string | null;
    youtube?: string | null;
    instagram?: string | null;
  };
  megaMenuDomestic?:
    | {
        title: string;
        icon?: string | null;
        iconBg?: string | null;
        links?:
          | {
              label: string;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  megaMenuInternational?:
    | {
        title: string;
        icon?: string | null;
        iconBg?: string | null;
        links?:
          | {
              label: string;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  whyChoose?:
    | {
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  footerAbout?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "touriza-settings_select".
 */
export interface TourizaSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logoUrl?: T;
  logo?: T;
  topbar?:
    | T
    | {
        hotline?: T;
        email?: T;
        address?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        primaryCta?: T;
        secondaryCta?: T;
        imageUrl?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  social?:
    | T
    | {
        facebook?: T;
        zalo?: T;
        youtube?: T;
        instagram?: T;
      };
  megaMenuDomestic?:
    | T
    | {
        title?: T;
        icon?: T;
        iconBg?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  megaMenuInternational?:
    | T
    | {
        title?: T;
        icon?: T;
        iconBg?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  whyChoose?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  footerAbout?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}